package translator

type TAInstructionType int

const (
	TAINSTR_TYPE_ASSIGN TAInstructionType = iota
	TAINSTR_TYPE_GOTO
	TAINSTR_TYPE_IF
	TAINSTR_TYPE_LABEL
	TAINSTR_TYPE_CALL
	TAINSTR_TYPE_RETURN
	TAINSTR_TYPE_SP
	TAINSTR_TYPE_PARAM
	TAINSTR_TYPE_FUNC_BEGIN
)
